CXX      = g++
CXXFLAGS = -std=c++17 -O2 -Wall

all: sort1 sort2 sort3

sort1: sort1.cc
	$(CXX) $(CXXFLAGS) -o sort1 sort1.cc

sort2: sort2.cc
	$(CXX) $(CXXFLAGS) -o sort2 sort2.cc

sort3: sort3.cc
	$(CXX) $(CXXFLAGS) -o sort3 sort3.cc

clean:
	rm -f sort1 sort2 sort3
